#!/usr/bin/env python
#
# simple fake zone generation tool
#
# gen-zone.py [TLD] [TARGET_FILE_NAME]
#
# expects both parameters or none
#
# By default, TLD=eu TARGET_FILE_NAME=eu.zone
#

import hashlib
import sys

TLD="eu"
ZONE_FILE=f"{TLD}.zone"

if len(sys.argv) != 1:
    if len(sys.argv) == 3:
        TLD = sys.argv[1]
        ZONE_FILE = sys.argv[2]
    else:
        print(f"""{sys.argv[0]} TLD ZONE-FILE_NAME
        
e.g.

  {sys.argv[0]} {TLD} {ZONE_FILE}""")
        exit(1)

print(f"called as: {sys.argv[0]} {TLD} {ZONE_FILE}")

# make something different from TLD
OTHER_TLD="ue" if TLD == "eu" else "eu"

TTL=86400

NS_POOL = ["somedns", "otherdns", "yetanotherdns", "andonemoredns"]
DS_ALG = [8, 10, 13, 14, 15, 16]

dnskey_tag_next = 12345

with open(f"{TLD}.zone", "w") as f:
    print(f";; generated by {sys.argv}\n", file=f)

    with open("tld.zone.head", "r") as h:
        head_text = h.read()
        print(head_text.replace("TLD", TLD), file=f)

    # NSEC3 (optout)
    print(f"{TLD}. 0 NSEC3PARAM 1 0 0 -", file=f)

    with open("names", "r") as n:
        while True:
            name = n.readline()

            if len(name) == 0:
                break

            name = name.strip()

            if len(name) == 0 or '#' in name:
                continue

            # some kind of hash to have some output variation
            number = 0
            for c in name:
                number = number * 97 + ord(c)
            #

            # glues or not
            if (number & 1) == 0:
                print(f"""{name}.{TLD}. {TTL} IN NS ns1.{name}.{TLD}.
{name}.{TLD}. {TTL} IN NS ns2.{name}.{TLD}.
ns1.{name}.{TLD}. {TTL} IN A 198.51.100.53
ns1.{name}.{TLD}. {TTL} IN AAAA 2001:DB8::1:35
ns2.{name}.{TLD}. {TTL} IN A 198.51.100.54
ns2.{name}.{TLD}. {TTL} IN AAAA 2001:DB8::1:36""", file=f)
            else: # (number & 1) ! = 0
                common_ns_name = NS_POOL[number % len(NS_POOL)]

                print(f"""{name}.{TLD}. {TTL} IN NS ns1.{common_ns_name}.{OTHER_TLD}.
{name}.{TLD}. {TTL} IN NS ns2.{common_ns_name}.{OTHER_TLD}.""", file=f)
            # has a DS
            if (number & 2) != 0:
                alg = DS_ALG[number % len(DS_ALG)]
                h = hashlib.sha256(name.encode())
                print(f"{name}.{TLD}. {TTL} IN DS {dnskey_tag_next} {alg} 2 {h.hexdigest()}", file=f)
                dnskey_tag_next = (dnskey_tag_next + 1000003) & 0xffff
            print("", file=f)
